In [3]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [10]:
arr = np.array(5) # 创建 0 维的 数组
print(arr)
print('arr 的维度:',arr.ndim)

5
arr 的维度: 0


In [13]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(arr)
print('arr 的维度:',arr.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
arr 的维度: 1


二维

In [16]:
arr = np.array([[1,2,3,4,5,],[10,11,12,13,14]])
print(arr)
print('arr 的维度:',arr.ndim)

[[ 1  2  3  4  5]
 [10 11 12 13 14]]
arr 的维度: 2


同质性
自动类型转换:


In [17]:
arr = np.array([1,'hello'])
print(arr)


['1' 'hello']


### 创建

In [18]:
# 基础
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
arr = np.ones((3,4),dtype=int)
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [32]:
arr = np.empty((3,4))
print(arr)

[[5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324]]


In [33]:
arr = np.full((3,4),5) # 形状+ 赋值
print(arr)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [35]:
arr_like = np.full_like(arr,2)
print(arr_like)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


# arange 范围

In [39]:
arr1 = np.arange(1, 10)
arr2 = np.arange(1, 10,2) # start值 end 值 step 步长
print(arr1)
print(arr2)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [41]:
arr= np.linspace(1,10,10)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [40]:
arr = np.logspace(1,3,5) # 对数 间隔
print(arr)

[  10.           31.6227766   100.          316.22776602 1000.        ]


# 索引和切片

In [51]:
#  一维数组
arr = np.random.randint(1,100,20)
print(arr)
print(arr[10])
print(arr[:])
print(arr[3:7])
print(arr[slice(3,7)]) #
print(arr[arr>30])

[86 77 44 43 76 95 31 60 15 45 53 50 72 78 16 99 54  7 60 85]
53
[86 77 44 43 76 95 31 60 15 45 53 50 72 78 16 99 54  7 60 85]
[43 76 95 31]
[43 76 95 31]
[86 77 44 43 76 95 31 60 45 53 50 72 78 99 54 60 85]


In [56]:
#  二维数组
arr = np.random.randint(1,100,(4,8)) # 4 行 8 列
print(arr)
print(arr[1,3]) # 行索引，列索引
print(arr[1,:]) # 第2行, 所有

[[48 76 44  6 10 69 52 16]
 [87 77 46 64 40 58 80 19]
 [92 78 61 51 58 86 76 96]
 [ 2 39 59 57 15 97 75 46]]
64
[87 77 46 64 40 58 80 19]
